on: 
  push: 
    branches: [ main ] 
 
jobs: 
  build: 
    runs-on: window-latest 
    steps: 
      - uses: actions/checkout@v4 
      - name: Set up JDK 
        uses: actions/setup-java@v4 
        with: 
          distribution: 'temurin' 
          java-version: '24' 
      - name: Build with Maven 
        run: mvn clean package 
 
      - name: Upload WAR artifact 
        uses: actions/upload-artifact@v4 
        with: 
          name: war-file 
          path: target/*.war 
 
  deploy: 
    needs: build 
    runs-on: window-latest 
    steps: 
      - uses: actions/download-artifact@v4 
        with: 
          name: war-file 
          path: . 
      - name: Deploy to Tomcat via curl 
        env: 
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }} 
          TOMCAT_PASS: ${{ secrets.TOMCAT_PASS }} 
        run: | 
          curl -v --upload-file Ramayan1.war \ 
            "http://localhost:8080/manager/text/deploy?path=/Ramayan1&update=true" \ 
            --user "$TOMCAT_USER:$TOMCAT_PASS"
